[package]
name = "zeth-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { git = "https://github.com/alloy-rs/core.git", rev = "58e2259", features = ["rlp", "serde"] }
alloy-rlp = { version = "0.3", default-features = false }
alloy-rlp-derive = { version = "0.3", default-features = false }
anyhow = "1.0"
bytes = { version = "1.1", default-features = false }
ethers-core = { version = "2.0", optional = true }
k256 = { version = "=0.13.1", features = ["std", "ecdsa"], default_features = false }
revm-primitives = { version = "1.1", optional = true }
rlp = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
sha2 = "=0.10.6"
sha3 = "0.10"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3"
hex-literal = "0.4"
serde_json = "1.0"

[features]
ethers = ["dep:ethers-core"]
revm = ["dep:revm-primitives"]
